version: '3.8'

services:
  node:
    build: .
    container_name: nestjs_rest_api
    image: 'pryvvid/nestjs_rest_api:node'
    ports: 
      - ${PORT}:${PORT}
    depends_on: 
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment: 
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
      - /usr/app/node_modules
    networks: 
      - bridge
    restart: always
  postgres:
    build: ./database/
    container_name: postgres_rest_api
    image: 'pryvvid/postgres_rest_api:postgres'
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes: 
      - ./database/pg:/var/lib/postgresql/data
    networks: 
      - bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks: 
  bridge:
    driver: bridge

