version: '3'

services:
  node:
    build: .
    container_name: node_rest_api
    ports: 
      - ${PORT}:${PORT}
    depends_on: 
      - postgres
    environment: 
      - PORT=${PORT}
    volumes:
      - .:/usr/app
      - ./logs:/usr/app/src/logs
    networks: 
      - bridge
    restart: always
  postgres:
    build: ./database/
    container_name: postgres_rest_api
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes: 
      - ./database/pg:/var/lib/postgresql/data
    networks: 
      - bridge
    restart: always

networks: 
  bridge:
    driver: bridge

